
apply plugin: 'com.android.application'

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localProperties.load(new FileInputStream(localPropertiesFile))
}
def brevoApiKey = localProperties.getProperty('brevo.api.key') ?: ""

android {
    namespace 'com.comismar.informes'
    compileSdk 34

    defaultConfig {
        applicationId "com.comismar.informes"
        minSdk 21
        targetSdk 34
        versionCode 5
        versionName "4.1"

        buildConfigField "String", "BREVO_API_KEY", "\"${brevoApiKey}\""

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildFeatures {
        buildConfig true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    packagingOptions {
        exclude 'META-INF/NOTICE.md'
        exclude 'META-INF/LICENSE.md'
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.room:room-common:2.6.1'
    implementation 'androidx.room:room-runtime:2.6.1'
    
    // Brevo API dependencies
    implementation 'com.squareup.okhttp3:okhttp:4.11.0'
    implementation 'com.google.code.gson:gson:2.10.1'
    
    // Background worker for API Key keep-alive
    implementation 'androidx.work:work-runtime:2.8.1'

    annotationProcessor 'androidx.room:room-compiler:2.6.1'
    implementation 'com.itextpdf:itextg:5.5.10'

}
